Open Router API and LOVO API
wass08/r3f-ai-language-teacher pull request #5
Opened 2024-12-24 01:45 UTC by sanjayy-22

I have added the open router and Lovo API in the last commit.

2024-12-27 09:23 UTC, wass08 requested changes
Looks great codewise, I still need to test it but if you can make the .env to .env.example change, then I'll do the tests and merge if it's good.
Thanks a lot for the great work!

2024-12-27 09:23 UTC, wass08 commented on .env
Can you rename this file to `.env.example`? As `.env` is generally the real one used (and it could lead to people pushing to the repo their real API Keys)

2024-12-27 13:34 UTC, sanjayy-22 commented on .env
@wass08 renamed the file names...

2024-12-27 16:12 UTC, sanjayy-22 commented
@wass08 done the changes ✅

2024-12-30 10:11 UTC, wass08 commented
@sanjayy-22 thank you, I'm having issues trying to run it (seems to be related to the package versions)
![image](https://github.com/user-attachments/assets/7688b16d-af61-4154-80ab-f2880f8ea9d2)

![image](https://github.com/user-attachments/assets/3c3ada48-828a-4c8b-b0d4-32a8e40fd850)

Did you face the same issues or know how to make it work?

2024-12-30 11:06 UTC, sanjayy-22 commented
> @sanjayy-22 thank you, I'm having issues trying to run it (seems to be related to the package versions)
> ![image](https://github.com/user-attachments/assets/7688b16d-af61-4154-80ab-f2880f8ea9d2)
> 
> ![image](https://github.com/user-attachments/assets/3c3ada48-828a-4c8b-b0d4-32a8e40fd850)
> 
> Did you face the same issues or know how to make it work?
> 

I didn't face any issues related with the package versions.
Try this command 

npm i @adaline/open-router

2024-12-31 11:34 UTC, wass08 commented
@sanjayy-22 same error
![image](https://github.com/user-attachments/assets/76239c98-55f6-4775-be65-a0ab1c4cdf12)

Can you clone your repository and check if a simple `yarn` and `yarn dev` work? If it doesn't please do the required fixes and commit them.

It doesn't work with npm too but please stick to yarn for this project as it's what was used for the tutorial. Locally you can use whatever you want as the `package.json` will be the same.

2024-12-31 11:39 UTC, sanjayy-22 commented
> @sanjayy-22 same error
> ![image](https://github.com/user-attachments/assets/76239c98-55f6-4775-be65-a0ab1c4cdf12)
> 
> Can you clone your repository and check if a simple `yarn` and `yarn dev` work? If it doesn't please do the required fixes and commit them.
> 
> It doesn't work with npm too but please stick to yarn for this project as it's what was used for the tutorial. Locally you can use whatever you want as the `package.json` will be the same.

I will check and confirm with you later 👍

2025-04-12 05:23 UTC, closed without merging